-- FeeZero Platform - New Language Translations
-- Vietnamese, Thai, Spanish, German translations for categories and skills

-- ===========================
-- Category Translations (Vietnamese)
-- ===========================
INSERT OR IGNORE INTO category_translations (category_id, language, name, description) VALUES
(1, 'vi', 'Phát triển & CNTT', 'Phát triển web, ứng dụng, phần mềm và dịch vụ CNTT'),
(2, 'vi', 'Phát triển Web', 'Website, ứng dụng web'),
(3, 'vi', 'Phát triển Ứng dụng Di động', 'Ứng dụng iOS, Android native/hybrid'),
(4, 'vi', 'Phát triển Phần mềm', 'Chương trình desktop, phát triển hệ thống'),
(5, 'vi', 'Phát triển Game', 'Game di động, PC, console'),
(6, 'vi', 'Cơ sở dữ liệu', 'Thiết kế, xây dựng, quản lý DB'),
(7, 'vi', 'AI/Học máy', 'Trí tuệ nhân tạo, phân tích dữ liệu'),
(8, 'vi', 'Blockchain', 'Hợp đồng thông minh, NFT, DeFi'),
(9, 'vi', 'DevOps', 'CI/CD, cơ sở hạ tầng đám mây'),
(10, 'vi', 'Thiết kế', 'Thiết kế UI/UX, đồ họa, web, v.v.'),
(11, 'vi', 'Thiết kế UI/UX', 'Thiết kế giao diện và trải nghiệm người dùng'),
(12, 'vi', 'Thiết kế Đồ họa', 'Logo, thương hiệu, ấn phẩm'),
(13, 'vi', 'Thiết kế Web', 'Thiết kế website responsive'),
(14, 'vi', 'Chỉnh sửa Video', 'Sản xuất video, đồ họa chuyển động'),
(15, 'vi', 'Mô hình 3D', 'Sản phẩm, nhân vật, kiến trúc 3D'),
(16, 'vi', 'Minh họa', 'Nhân vật, nền, concept art'),
(17, 'vi', 'Marketing & Kinh doanh', 'Marketing kỹ thuật số, thương hiệu, tư vấn'),
(18, 'vi', 'Marketing Kỹ thuật số', 'SEO, SEM, marketing mạng xã hội'),
(19, 'vi', 'Marketing Nội dung', 'Tạo nội dung blog, YouTube'),
(20, 'vi', 'Thương hiệu', 'Chiến lược thương hiệu, phát triển CI/BI'),
(21, 'vi', 'Nghiên cứu Thị trường', 'Phân tích cạnh tranh, nghiên cứu người tiêu dùng'),
(22, 'vi', 'Tư vấn Kinh doanh', 'Chiến lược kinh doanh, cải tiến quy trình'),
(23, 'vi', 'Viết & Dịch thuật', 'Viết nội dung, dịch thuật, copywriting'),
(24, 'vi', 'Viết Nội dung', 'Blog, bài báo, nội dung web'),
(25, 'vi', 'Dịch thuật', 'Dịch tài liệu đa ngôn ngữ'),
(26, 'vi', 'Copywriting', 'Nội dung quảng cáo, bản sao marketing'),
(27, 'vi', 'Viết Kỹ thuật', 'Hướng dẫn, tài liệu API'),
(28, 'vi', 'Tài liệu Pháp lý', 'Hợp đồng, điều khoản dịch vụ'),
(29, 'vi', 'Khác', 'Nhập dữ liệu, công việc hành chính, v.v.'),
(30, 'vi', 'Nhập Dữ liệu', 'Công việc tài liệu, sắp xếp dữ liệu'),
(31, 'vi', 'Trợ lý Ảo', 'Hỗ trợ hành chính'),
(32, 'vi', 'Tư vấn Pháp lý', 'Tư vấn hợp đồng, sở hữu trí tuệ'),
(33, 'vi', 'Tài chính/Kế toán', 'Thuế, chuẩn bị báo cáo tài chính');

-- ===========================
-- Category Translations (Thai)
-- ===========================
INSERT OR IGNORE INTO category_translations (category_id, language, name, description) VALUES
(1, 'th', 'การพัฒนาและไอที', 'การพัฒนาเว็บ แอป ซอฟต์แวร์ และบริการไอที'),
(2, 'th', 'การพัฒนาเว็บ', 'เว็บไซต์ แอปพลิเคชันเว็บ'),
(3, 'th', 'การพัฒนาแอปมือถือ', 'แอป iOS, Android แบบ native/hybrid'),
(4, 'th', 'การพัฒนาซอฟต์แวร์', 'โปรแกรมเดสก์ท็อป การพัฒนาระบบ'),
(5, 'th', 'การพัฒนาเกม', 'เกมมือถือ PC คอนโซล'),
(6, 'th', 'ฐานข้อมูล', 'การออกแบบ สร้าง จัดการ DB'),
(7, 'th', 'AI/การเรียนรู้ของเครื่อง', 'ปัญญาประดิษฐ์ การวิเคราะห์ข้อมูล'),
(8, 'th', 'บล็อกเชน', 'สัญญาอัจฉริยะ NFT DeFi'),
(9, 'th', 'DevOps', 'CI/CD โครงสร้างพื้นฐานคลาวด์'),
(10, 'th', 'การออกแบบ', 'การออกแบบ UI/UX กราฟิก เว็บ ฯลฯ'),
(11, 'th', 'การออกแบบ UI/UX', 'การออกแบบส่วนติดต่อผู้ใช้และประสบการณ์'),
(12, 'th', 'การออกแบบกราฟิก', 'โลโก้ แบรนด์ สิ่งพิมพ์'),
(13, 'th', 'การออกแบบเว็บ', 'การออกแบบเว็บไซต์แบบ responsive'),
(14, 'th', 'การตัดต่อวิดีโอ', 'การผลิตวิดีโอ motion graphics'),
(15, 'th', 'การสร้างแบบจำลอง 3D', 'ผลิตภัณฑ์ ตัวละคร สถาปัตยกรรม 3D'),
(16, 'th', 'ภาพประกอบ', 'ตัวละคร พื้นหลัง concept art'),
(17, 'th', 'การตลาดและธุรกิจ', 'การตลาดดิจิทัล แบรนด์ ที่ปรึกษา'),
(18, 'th', 'การตลาดดิจิทัล', 'SEO SEM การตลาดโซเชียลมีเดีย'),
(19, 'th', 'การตลาดเนื้อหา', 'การสร้างเนื้อหาบล็อก YouTube'),
(20, 'th', 'การสร้างแบรนด์', 'กลยุทธ์แบรนด์ การพัฒนา CI/BI'),
(21, 'th', 'การวิจัยตลาด', 'การวิเคราะห์คู่แข่ง การวิจัยผู้บริโภค'),
(22, 'th', 'ที่ปรึกษาธุรกิจ', 'กลยุทธ์ธุรกิจ การปรับปรุงกระบวนการ'),
(23, 'th', 'การเขียนและการแปล', 'การเขียนเนื้อหา การแปล copywriting'),
(24, 'th', 'การเขียนเนื้อหา', 'บล็อก บทความ เนื้อหาเว็บ'),
(25, 'th', 'การแปล', 'การแปลเอกสารหลายภาษา'),
(26, 'th', 'Copywriting', 'ข้อความโฆษณา สำเนาการตลาด'),
(27, 'th', 'การเขียนทางเทคนิค', 'คู่มือ เอกสาร API'),
(28, 'th', 'เอกสารทางกฎหมาย', 'สัญญา ข้อกำหนดการใช้บริการ'),
(29, 'th', 'อื่นๆ', 'การป้อนข้อมูล งานธุรการ ฯลฯ'),
(30, 'th', 'การป้อนข้อมูล', 'งานเอกสาร การจัดระเบียบข้อมูล'),
(31, 'th', 'ผู้ช่วยเสมือน', 'การสนับสนุนด้านธุรการ'),
(32, 'th', 'คำปรึกษาทางกฎหมาย', 'คำปรึกษาสัญญา ทรัพย์สินทางปัญญา'),
(33, 'th', 'การเงิน/การบัญชี', 'ภาษี การจัดทำงบการเงิน');

-- ===========================
-- Category Translations (Spanish)
-- ===========================
INSERT OR IGNORE INTO category_translations (category_id, language, name, description) VALUES
(1, 'es', 'Desarrollo e IT', 'Desarrollo web, aplicaciones, software y servicios IT'),
(2, 'es', 'Desarrollo Web', 'Sitios web, aplicaciones web'),
(3, 'es', 'Desarrollo de Aplicaciones Móviles', 'Aplicaciones iOS, Android nativas/híbridas'),
(4, 'es', 'Desarrollo de Software', 'Programas de escritorio, desarrollo de sistemas'),
(5, 'es', 'Desarrollo de Juegos', 'Juegos móviles, PC, consola'),
(6, 'es', 'Base de Datos', 'Diseño, construcción, gestión de BD'),
(7, 'es', 'IA/Aprendizaje Automático', 'Inteligencia artificial, análisis de datos'),
(8, 'es', 'Blockchain', 'Contratos inteligentes, NFT, DeFi'),
(9, 'es', 'DevOps', 'CI/CD, infraestructura en la nube'),
(10, 'es', 'Diseño', 'Diseño UI/UX, gráfico, web, etc.'),
(11, 'es', 'Diseño UI/UX', 'Diseño de interfaz y experiencia de usuario'),
(12, 'es', 'Diseño Gráfico', 'Logo, branding, materiales impresos'),
(13, 'es', 'Diseño Web', 'Diseño de sitio web responsive'),
(14, 'es', 'Edición de Video', 'Producción de video, motion graphics'),
(15, 'es', 'Modelado 3D', 'Producto, personaje, arquitectura 3D'),
(16, 'es', 'Ilustración', 'Personaje, fondo, concept art'),
(17, 'es', 'Marketing y Negocios', 'Marketing digital, branding, consultoría'),
(18, 'es', 'Marketing Digital', 'SEO, SEM, marketing en redes sociales'),
(19, 'es', 'Marketing de Contenidos', 'Creación de contenido para blog, YouTube'),
(20, 'es', 'Branding', 'Estrategia de marca, desarrollo CI/BI'),
(21, 'es', 'Investigación de Mercado', 'Análisis competitivo, investigación del consumidor'),
(22, 'es', 'Consultoría Empresarial', 'Estrategia empresarial, mejora de procesos'),
(23, 'es', 'Redacción y Traducción', 'Redacción de contenido, traducción, copywriting'),
(24, 'es', 'Redacción de Contenidos', 'Blog, artículos, contenido web'),
(25, 'es', 'Traducción', 'Traducción de documentos multilingües'),
(26, 'es', 'Copywriting', 'Texto publicitario, copy de marketing'),
(27, 'es', 'Redacción Técnica', 'Manuales, documentación de API'),
(28, 'es', 'Documentos Legales', 'Contratos, términos de servicio'),
(29, 'es', 'Otros', 'Entrada de datos, tareas administrativas, etc.'),
(30, 'es', 'Entrada de Datos', 'Trabajo de documentos, organización de datos'),
(31, 'es', 'Asistente Virtual', 'Soporte administrativo'),
(32, 'es', 'Consultoría Legal', 'Asesoramiento sobre contratos, propiedad intelectual'),
(33, 'es', 'Finanzas/Contabilidad', 'Impuestos, preparación de estados financieros');

-- ===========================
-- Category Translations (German)
-- ===========================
INSERT OR IGNORE INTO category_translations (category_id, language, name, description) VALUES
(1, 'de', 'Entwicklung & IT', 'Web-, App-, Softwareentwicklung und IT-Dienste'),
(2, 'de', 'Webentwicklung', 'Websites, Webanwendungen'),
(3, 'de', 'Mobile App-Entwicklung', 'iOS-, Android-Native-/Hybrid-Apps'),
(4, 'de', 'Softwareentwicklung', 'Desktop-Programme, Systementwicklung'),
(5, 'de', 'Spieleentwicklung', 'Mobile-, PC-, Konsolenspiele'),
(6, 'de', 'Datenbank', 'DB-Design, Aufbau, Verwaltung'),
(7, 'de', 'KI/Maschinelles Lernen', 'Künstliche Intelligenz, Datenanalyse'),
(8, 'de', 'Blockchain', 'Smart Contracts, NFT, DeFi'),
(9, 'de', 'DevOps', 'CI/CD, Cloud-Infrastruktur'),
(10, 'de', 'Design', 'UI/UX-, Grafik-, Webdesign usw.'),
(11, 'de', 'UI/UX-Design', 'Benutzeroberflächen- und Erfahrungsdesign'),
(12, 'de', 'Grafikdesign', 'Logo, Branding, Druckmaterialien'),
(13, 'de', 'Webdesign', 'Responsive Website-Design'),
(14, 'de', 'Videobearbeitung', 'Videoproduktion, Motion Graphics'),
(15, 'de', '3D-Modellierung', 'Produkt-, Charakter-, Architektur-3D'),
(16, 'de', 'Illustration', 'Charakter, Hintergrund, Concept Art'),
(17, 'de', 'Marketing & Business', 'Digitales Marketing, Branding, Beratung'),
(18, 'de', 'Digitales Marketing', 'SEO, SEM, Social-Media-Marketing'),
(19, 'de', 'Content-Marketing', 'Blog-, YouTube-Content-Erstellung'),
(20, 'de', 'Branding', 'Markenstrategie, CI/BI-Entwicklung'),
(21, 'de', 'Marktforschung', 'Wettbewerbsanalyse, Verbraucherforschung'),
(22, 'de', 'Unternehmensberatung', 'Geschäftsstrategie, Prozessverbesserung'),
(23, 'de', 'Schreiben & Übersetzung', 'Content-Schreiben, Übersetzung, Copywriting'),
(24, 'de', 'Content-Schreiben', 'Blog, Artikel, Webinhalte'),
(25, 'de', 'Übersetzung', 'Mehrsprachige Dokumentenübersetzung'),
(26, 'de', 'Copywriting', 'Werbetext, Marketing-Copy'),
(27, 'de', 'Technisches Schreiben', 'Handbücher, API-Dokumentation'),
(28, 'de', 'Rechtsdokumente', 'Verträge, Nutzungsbedingungen'),
(29, 'de', 'Sonstiges', 'Dateneingabe, Verwaltungsaufgaben usw.'),
(30, 'de', 'Dateneingabe', 'Dokumentenarbeit, Datenorganisation'),
(31, 'de', 'Virtueller Assistent', 'Administrative Unterstützung'),
(32, 'de', 'Rechtsberatung', 'Vertrags-, Urheberrechtsberatung'),
(33, 'de', 'Finanzen/Buchhaltung', 'Steuern, Jahresabschlusserstellung');

-- ===========================
-- Skill Translations (Vietnamese, Thai, Spanish, German)
-- ===========================

-- Vietnamese
INSERT OR IGNORE INTO skill_translations (skill_id, language, name) VALUES
(1, 'vi', 'JavaScript'),
(2, 'vi', 'TypeScript'),
(3, 'vi', 'Python'),
(4, 'vi', 'Java'),
(5, 'vi', 'Swift'),
(6, 'vi', 'Kotlin'),
(7, 'vi', 'React'),
(8, 'vi', 'Vue.js'),
(9, 'vi', 'Angular'),
(10, 'vi', 'Node.js'),
(11, 'vi', 'Figma'),
(12, 'vi', 'Adobe XD'),
(13, 'vi', 'Photoshop'),
(14, 'vi', 'Illustrator'),
(15, 'vi', 'After Effects'),
(16, 'vi', 'Blender'),
(17, 'vi', 'SEO'),
(18, 'vi', 'Quảng cáo Google'),
(19, 'vi', 'Quảng cáo Facebook'),
(20, 'vi', 'Chiến lược Nội dung');

-- Thai
INSERT OR IGNORE INTO skill_translations (skill_id, language, name) VALUES
(1, 'th', 'JavaScript'),
(2, 'th', 'TypeScript'),
(3, 'th', 'Python'),
(4, 'th', 'Java'),
(5, 'th', 'Swift'),
(6, 'th', 'Kotlin'),
(7, 'th', 'React'),
(8, 'th', 'Vue.js'),
(9, 'th', 'Angular'),
(10, 'th', 'Node.js'),
(11, 'th', 'Figma'),
(12, 'th', 'Adobe XD'),
(13, 'th', 'Photoshop'),
(14, 'th', 'Illustrator'),
(15, 'th', 'After Effects'),
(16, 'th', 'Blender'),
(17, 'th', 'SEO'),
(18, 'th', 'โฆษณา Google'),
(19, 'th', 'โฆษณา Facebook'),
(20, 'th', 'กลยุทธ์เนื้อหา');

-- Spanish
INSERT OR IGNORE INTO skill_translations (skill_id, language, name) VALUES
(1, 'es', 'JavaScript'),
(2, 'es', 'TypeScript'),
(3, 'es', 'Python'),
(4, 'es', 'Java'),
(5, 'es', 'Swift'),
(6, 'es', 'Kotlin'),
(7, 'es', 'React'),
(8, 'es', 'Vue.js'),
(9, 'es', 'Angular'),
(10, 'es', 'Node.js'),
(11, 'es', 'Figma'),
(12, 'es', 'Adobe XD'),
(13, 'es', 'Photoshop'),
(14, 'es', 'Illustrator'),
(15, 'es', 'After Effects'),
(16, 'es', 'Blender'),
(17, 'es', 'SEO'),
(18, 'es', 'Anuncios de Google'),
(19, 'es', 'Anuncios de Facebook'),
(20, 'es', 'Estrategia de Contenido');

-- German
INSERT OR IGNORE INTO skill_translations (skill_id, language, name) VALUES
(1, 'de', 'JavaScript'),
(2, 'de', 'TypeScript'),
(3, 'de', 'Python'),
(4, 'de', 'Java'),
(5, 'de', 'Swift'),
(6, 'de', 'Kotlin'),
(7, 'de', 'React'),
(8, 'de', 'Vue.js'),
(9, 'de', 'Angular'),
(10, 'de', 'Node.js'),
(11, 'de', 'Figma'),
(12, 'de', 'Adobe XD'),
(13, 'de', 'Photoshop'),
(14, 'de', 'Illustrator'),
(15, 'de', 'After Effects'),
(16, 'de', 'Blender'),
(17, 'de', 'SEO'),
(18, 'de', 'Google-Anzeigen'),
(19, 'de', 'Facebook-Anzeigen'),
(20, 'de', 'Content-Strategie');
